name: Update UserScript

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command
    - name: Run build
      uses: borales/actions-yarn@v4
      with:
        cmd: build # will run `yarn build` command

    - name: Commit and push
      uses: actions-js/push@v1.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: 'action:  Update UserScript'

    - name: Format dist files
      run: mkdir export && cp README.md ./export/TsingHuaELT-Workflow.md && cp ./dist/main.user.js ./export/TsingHuaELT-Workflow.user.js 
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: tsinghuaelt-workflow
        path: |
          ./export/TsingHuaELT-Workflow.md
          ./export/TsingHuaELT-Workflow.user.js

  push-to-userjs:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout user.js repository
      uses: actions/checkout@v4
      with:
        repository: lcandy2/user.js
        token: ${{ secrets.ACCESS_TOKEN }} # Make sure to set this in your repo secrets
        path: ./export/user-js

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: tsinghuaelt-workflow
        path: ./export/user-js/tsinghuaelt.com/

    - name: Commit and push to user.js
      uses: actions-js/push@v1.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository: lcandy2/user.js
        directory: ./export/user-js
        message: 'action: Update TsingHuaELT-Workflow'